name: Actualizar Entradas transporte

on:

  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"

jobs:

  actualizar:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python Transporte.py

      - name: Commit CSV
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add historico_entradas_transporte.csv

          git diff --cached --quiet || git commit -m "Actualización GNL"

          git push
